### ISSUE TITLE
rpmemd: invalid data logged to syslog

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#622]
Prefix `#011` is added to some logs when logging to syslog. 
Steps to reproduce:
```
1. Raise logging level in daemon configuration file to debug level.
2. Create/close remote pool
```
Logs:
```
rpmemd version 1.3-102-g0ca438f
ssh connection: 192.168.0.181 35160 192.168.0.182 22
user: root
configuration
#011pool set directory: '/user'
#011persist method: General Purpose Server Persistency Method
#011number of threads: 28
create request:
#011pool descriptor: 'pool.set'
#011pool size: 20971520
#011nlanes: 1024
#011provider: verbs
pool attributes:
#011signature: ''
#011major: 0
#011compat_features: 0x0
#011incompat_features: 0x0
#011ro_compat_features: 0x0
#011poolset_uuid: 00000000-0000-0000-0000-000000000000
#011uuid: 00000000-0000-0000-0000-000000000000
#011next_uuid: 00000000-0000-0000-0000-000000000000
#011prev_uuid: 00000000-0000-0000-0000-000000000000
persistency policy:
#011persist method: General Purpose Server Persistency Method
#011persist flush: pmem_msync
libfabric version: 1.4.2
libfabric interface info:
fi_info:
   caps: [ FI_MSG, FI_RMA ]
   mode: [ FI_LOCAL_MR ]
   addr_format: FI_SOCKADDR_IN
   src_addrlen: 16
   dest_addrlen: 0
   src_addr: 192.168.0.182
   dest_addr: (null)
   handle: (null)
   fi_tx_attr:
       caps: [  ]
       mode: [ FI_LOCAL_MR ]
       op_flags: [  ]
       msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
       comp_order: [  ]
       inject_size: 88
       size: 495
       iov_limit: 6
       rma_iov_limit: 1
   fi_rx_attr:
       caps: [  ]
       mode: [ FI_RX_CQ_DATA, FI_LOCAL_MR ]
       op_flags: [  ]
       msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
       comp_order: [  ]
       total_buffered_recv: 0
       size: 512
       iov_limit: 4
   fi_ep_attr:
       type: FI_EP_MSG
       protocol: FI_PROTO_RDMA_CM_IB_RC
       protocol_version: 1
       max_msg_size: 1073741824
       msg_prefix_size: 0
       max_order_raw_size: 1073741824
       max_order_war_size: 0
       max_order_waw_size: 1073741824
       mem_tag_format: 0x0000000000000000
       tx_ctx_cnt: 1
       rx_ctx_cnt: 1
   fi_domain_attr:
       domain: 0x0
       name: mlx4_0
       threading: FI_THREAD_SAFE
       control_progress: FI_PROGRESS_AUTO
       data_progress: FI_PROGRESS_AUTO
       resource_mgmt: FI_RM_UNSPEC
       av_type: FI_AV_UNSPEC
       mr_mode: FI_MR_BASIC
       mr_key_size: 4
       cq_data_size: 4
       cq_cnt: 65408
       ep_cnt: 130488
       tx_ctx_cnt: 1024
       rx_ctx_cnt: 1024
       max_ep_tx_ctx: 130488
       max_ep_rx_ctx: 130488
       max_ep_stx_ctx: 0
       max_ep_srx_ctx: 0
   fi_fabric_attr:
       name: IB-0x80fe
       prov_name: verbs
       prov_version: 1.0

create request response: (status = 0)
#011port: 49398
#011rkey: 0x18010169
#011raddr: 0x7fc5dfc01000
#011nlanes: 1024
#011persist method: General Purpose Server Persistency Method
waiting for in-band connection
in-band connection established
close request
closing pool
pool closed
close request response (status = 0)
rpmemd version 1.3-102-g0ca438f
removing 'pool.set'
removed 'pool.set'
```
There is no such a redundant prefix when logging to file instead of syslog.
Found on  1.3-102-g0ca438f
